# Generated by Django 4.0.6 on 2022-08-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Содержание записи')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Запись создана')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Запись изменена')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ('-updated', '-created'),
            },
        ),
    ]
